-- Seed: initial site content (generated by scripts/make-seed-sql.mjs from content.ts).
-- Idempotent: portfolios/services/skills are only inserted when missing.

insert into public.portfolios (slug, title, category, summary, description, tech_stack, live_url, repo_url, status, featured, order_index, published_at) values
  ('titikpoin', 'Titikpoin', 'Web', 'Gamified learning platform with points, quests and live class tools.', 'A learning platform where students earn points for finishing quests, joining live sessions and helping peers. Teachers get a dashboard to build modules, track progress and run quizzes in class.', array['Next.js', 'TypeScript', 'Laravel', 'MySQL', 'Redis']::text[], null, 'https://github.com/raydiansyah', 'published', true, 0, make_date(2025, 1, 1)::timestamptz),
  ('lsp-tik', 'LSP TIK', 'Web', 'End-to-end competency certification: registration, assessment, certificates.', 'A certification system for an ICT professional certification body. Candidates register and upload evidence, assessors score competency units, and certificates are issued with verifiable QR codes.', array['Laravel', 'Livewire', 'MySQL', 'Tailwind CSS']::text[], null, 'https://github.com/raydiansyah', 'published', true, 1, make_date(2024, 1, 1)::timestamptz),
  ('marketplace', 'Marketplace', 'Web', 'One stock, many channels — sync orders across marketplaces and a web store.', 'An omnichannel commerce back office that keeps stock, pricing and orders in sync across several marketplaces and a branded web store, built from lessons learned running my own online shop.', array['React', 'Node.js', 'PostgreSQL', 'Queues', 'Docker']::text[], null, 'https://github.com/raydiansyah', 'published', true, 2, make_date(2024, 1, 1)::timestamptz),
  ('saas', 'SaaS Project', 'Web', 'Multi-tenant management platform for teams, billing and reporting.', 'A multi-tenant SaaS for small organisations to manage members, schedules and invoices, with role-based access and exportable reports.', array['Vue', 'Laravel', 'MySQL', 'Stripe']::text[], null, 'https://github.com/raydiansyah', 'published', true, 3, make_date(2023, 1, 1)::timestamptz),
  ('fintrack', 'FinTrack Mobile', 'Mobile', 'Personal finance tracker with receipt scanning and auto-categorisation.', 'A Flutter app that scans receipts with OCR and categorises expenses automatically.', array['Flutter', 'Firebase', 'ML Kit']::text[], null, null, 'published', false, 4, make_date(2023, 1, 1)::timestamptz),
  ('python-module', 'Corporate Python Module', 'Training', 'Automation-focused Python curriculum for corporate workshops.', 'A modular curriculum for corporate Python workshops, focused on automating everyday office work.', array['Python', 'Pandas', 'Jupyter']::text[], null, null, 'published', false, 5, make_date(2022, 1, 1)::timestamptz),
  ('mqtt', 'Smart Home MQTT API', 'Open Source', 'Lightweight Go library for MQTT messaging on IoT devices.', 'A small Go library that wraps MQTT messaging patterns for home-automation devices.', array['Go', 'MQTT', 'Docker']::text[], null, 'https://github.com/raydiansyah', 'published', false, 6, make_date(2021, 1, 1)::timestamptz)
on conflict (slug) do nothing;

insert into public.services (icon, name, description, is_active, order_index)
select v.icon, v.name, v.description, true, v.ord from (values
  ('Globe', 'Web platforms', 'Product-grade web apps: dashboards, portals, learning and commerce systems.', 0),
  ('Sparkles', 'Interactive experiences', 'Landing pages and storytelling sites with WebGL and motion that still load fast.', 1),
  ('GraduationCap', 'IT training', 'Hands-on workshops and curricula for teams, schools and institutions.', 2),
  ('Compass', 'Technical consulting', 'Audits and second opinions on codebases, stacks and delivery process.', 3)
) as v(icon, name, description, ord)
where not exists (select 1 from public.services x where x.name = v.name);

insert into public.skills (name, category, level, order_index)
select v.name, v.category::public.skill_category, v.level, v.ord from (values
  ('TypeScript', 'frontend', 92, 0),
  ('React', 'frontend', 90, 1),
  ('Next.js', 'frontend', 85, 2),
  ('Laravel', 'backend', 88, 3),
  ('Node.js', 'backend', 82, 4),
  ('MySQL', 'backend', 80, 5),
  ('PostgreSQL', 'backend', 78, 6),
  ('Docker', 'devops', 70, 7),
  ('Three.js', 'frontend', 65, 8)
) as v(name, category, level, ord)
where not exists (select 1 from public.skills x where x.name = v.name);

update public.settings set site_name = 'Ray Diansyah — Harbor' where id = 1 and site_name = 'Ray Diansyah';
